### ISSUE TITLE
Remove INTERNET permission for non-Bugnag enabled builds

### ISSUE THREAD

**Issue by licaon-kter** [xyzz/openmw-android#33]
...as this is not needed.

**Comment by xyzz** [comment]
Not really interested in fixing this for the following reasons:

- non-bugsnag builds aren't a flavor, and I don't see any other way to change the manifest. I don't want to make them a flavor either, because that would just add more complexity for no (IMO) benefit
- tes3mp eventually is getting merged into openmw, at which point I plan to support it in the android port, so the permission would need to be re-introduced at that time.
