### ISSUE TITLE
Expose settings-default.cfg file to the user

### ISSUE THREAD

**Issue by AbduSharif** [xyzz/openmw-android#44]
settings-default.cfg file is rather important and mentions settings that are useful to the user that there's no way of finding them other than searching on the internet.

So it should be extracted to the openmw folder that's in the internal storage.

**Comment by xyzz** [comment]
unfortunately past experience has shown that exposing these files results in users editing them and complaining when things break during upgrade. Since this is a -default file, it has to be in sync with openmw code base, and to achieve that it is overwritten on update without tracking user changes. For the actual list of options I suggest referring to https://openmw.readthedocs.io/en/stable/reference/modding/settings/

**Comment by AbduSharif** [comment]
While asking users to refer to the documented settings is better, but sometimes some settings didn't make it there that are only mentioned in settings-default.cfg, for example the recently merged distant statics feature, it's only available in the current nightlies, and it's settings currently are only mentioned in settings-default.cfg.

Also users won't automatically know that there are other settings that could be found in that link, so I suggest to at least make the file readable from an option in the three dot menu, but not editable.
