### ISSUE TITLE
Long loading time on Android 11

### ISSUE THREAD

**Issue by j13u11fr09** [xyzz/openmw-android#59]
**Describe the bug**
When you hit the "play" button in the bottom right of the launcher app, it takes about a minute and a half to start the game. At first I thought the app had frozen, but after waiting a long time the game does start. 

Loading and saving also seem to take longer under Android 11 so I'm thinking this may have something to do with how storage is handled under Android 11.

This also happens with the stable version of OpenMW.

**To Reproduce**
1. Open the OpenMW launcher app
2. Click on the play button.
3. Wait... About a minute and a half for the game to launch

**Expected behavior**
On an older phone running Android 10 (Pixel XL) the game loads almost instantly. No wait.

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a 5g
 - OS: Android 11
 - Version: 0.47.0-41-nightly and 0.46.0-38
 - App source: Google Play store

**Comment by licaon-kter** [comment]
Same setup? Mods? Distant land?

**Comment by j13u11fr09** [comment]
Same setup as under Android 10, yup. I've tried disabling all mods and deleting my settings.cfg file: no change.

**Comment by xyzz** [comment]
It's getting stuck in `VFS::FileSystemArchive::listResources`, the reason is new google's file access framework (that is automatically used for file access under /sdcard) is incredibly slow, as described in https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/. Not sure there's anything I can do about it, one thing you can try is packing loose files into a .bsa.

**Comment by j13u11fr09** [comment]
Ok, thanks for looking into it, I kind of figured this might be beyond your control. I haven't had a chance to time it yet, but it did seem to speed up after the last Android update.

Thanks again!
