### ISSUE TITLE
Play Store - OMW Stable "Incompatible with device"

### ISSUE THREAD

**Issue by SuttonX** [xyzz/openmw-android#92]
In the Google Play Store, OMW stable version shows incompatible with my Samsung Galaxy S20 Plus. It only shows Nightly as compatible.

However, when I manually download the stable version from here and install it, it actually runs smoother for me than the Nightly version does. The stable version is MORE compatible for my device.

Please update your APK metadata and/or Play Store listing to let Google know that it is, in fact, compatible with my device. Just check it against whatever you have listed for Nightly.

**Comment by xyzz** [comment]
Samsung devices which received android 11 update were manually excluded due to #63

Basically, Samsung broke/changed something wrt touch controls in 11 (which is not reproducible on other manufacturers' devices), and samsung users were posting a lot of 1-star reviews due to controls not working properly, so it's temporarily excluded.

Unfortunately I don't have any samsung devices so at the moment I cannot reproduce or fix the bug.

**Comment by SuttonX** [comment]
I am not experiencing the issue in #63 on my Samsung with Android 11. The stable version side-loaded actually performs better than Nightly for me.

The only issue I have is that I can't use the touch screen to directly select menu choices in-game, however I can just use the virtual joysticks to scroll to them.
